interface:
  html:
    #list   : []
    insert : insertUpdate.html 
    update : insertUpdate.html 
    dummy  : insertUpdate.html 
  css:
    list   : [] 
    insert : [] 
    update : [] 
    dummy  : [] 
  javascript:
    head:
      list   : [] 
      insert : [ "ckeditor/ckeditor.js", "insertUpdate.js" ] 
      update : [ "ckeditor/ckeditor.js", "insertUpdate.js" ] 
      dummy  : [ "ckeditor/ckeditor.js", "insertUpdate.js" ] 
    body:
      list   : [] 
      insert : [ "javascript.js" ]  
      update : [ "javascript.js" ]  
      dummy  : [ "javascript.js" ] 
default:
  parameter : 
    extraPlugins          : 'autogrow'
    autoGrow_maxHeight    : 800
    removePlugins         : 'resize'
    toolbarCanCollapse    : true
    toolbarStartupExpanded: false
    toolbar: 
      - name: 'document'
        items: [ 'Source' ]
        
      - name: 'clipboard'
        items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ]

      - name: 'forms'
        items: [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ]
      
      - name  : 'editing'
        items : [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ]

      - name  : 'basicstyles'
        items : [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]

      - name  : 'paragraph'
        items : [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl' ]

      - name : 'links'
        items: [ 'Link', 'Unlink', 'Anchor' ]

      - name : 'insert'
        items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ]

      - name : 'styles'
        items: [ 'Styles', 'Format', 'Font', 'FontSize' ]

      - name : 'colors'
        items: [ 'TextColor', 'BGColor' ]

      - name : 'tools'
        items: [ 'Maximize', 'ShowBlocks' ]

      - name : 'others'
        items: [ 'MediaEmbed', '-' ]