interface:
  html:
   #list   : list.html   
    insert : 'insertAndUpdate.html'
    update : 'insertAndUpdate.html'
    dummy  : 'insertAndUpdate.html'
  css:
    list   : []   
    insert : [ 'style.css' ]   
    update : [ 'style.css' ]   
    dummy  : [ 'style.css' ]   
  javascript:
    head:
      list   : []
      insert : []
      update : []
      dummy  : [] 
    body:
      list   : []
      insert : []
      update : []
      dummy  : [] 
default:
  parameter : []